name: Build Claude Runner Image

on:
  push:
    paths:
      - 'docker/**'
      - 'package*.json'
      - '.github/workflows/build-claude-runner.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/claude-runner.dockerfile
          push: true
          tags: |
            ghcr.io/clharman/dev-tools/claude-runner:latest
            ghcr.io/clharman/dev-tools/claude-runner:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64